config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :place_ratings
  resources :visitor_reviews
  resources :places_to_visits
  devise_for :users
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/visitor_reviews_controller.rb
class VisitorReviewsController < ApplicationController
  before_action :set_visitor_review, only: [:show, :edit, :update, :destroy]

  # GET /visitor_reviews
  # GET /visitor_reviews.json
  def index
    @visitor_reviews = VisitorReview.all
  end

  # GET /visitor_reviews/1
  # GET /visitor_reviews/1.json
  def show
  end

  # GET /visitor_reviews/new
  def new
    @visitor_review = VisitorReview.new
  end

  # GET /visitor_reviews/1/edit
  def edit
  end

  # POST /visitor_reviews
  # POST /visitor_reviews.json
  def create
    @visitor_review = VisitorReview.new(visitor_review_params)

    respond_to do |format|
      if @visitor_review.save
        format.html { redirect_to @visitor_review, notice: 'Visitor review was successfully created.' }
        format.json { render :show, status: :created, location: @visitor_review }
      else
        format.html { render :new }
        format.json { render json: @visitor_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitor_reviews/1
  # PATCH/PUT /visitor_reviews/1.json
  def update
    respond_to do |format|
      if @visitor_review.update(visitor_review_params)
        format.html { redirect_to @visitor_review, notice: 'Visitor review was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitor_review }
      else
        format.html { render :edit }
        format.json { render json: @visitor_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitor_reviews/1
  # DELETE /visitor_reviews/1.json
  def destroy
    @visitor_review.destroy
    respond_to do |format|
      format.html { redirect_to visitor_reviews_url, notice: 'Visitor review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor_review
      @visitor_review = VisitorReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visitor_review_params
      params.fetch(:visitor_review, {})
    end
end

app/helpers/visitor_reviews_helper.rb
module VisitorReviewsHelper
end

app/views/visitor_reviews/_form.html.erb
<%= form_with(model: visitor_review, local: true) do |form| %>
  <% if visitor_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visitor_review.errors.count, "error") %> prohibited this visitor_review from being saved:</h2>

      <ul>
      <% visitor_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/visitor_reviews/edit.html.erb
<h1>Editing Visitor Review</h1>

<%= render 'form', visitor_review: @visitor_review %>

<%= link_to 'Show', @visitor_review %> |
<%= link_to 'Back', visitor_reviews_path %>

app/views/visitor_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Visitor Reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visitor_reviews.each do |visitor_review| %>
      <tr>
        <td><%= link_to 'Show', visitor_review %></td>
        <td><%= link_to 'Edit', edit_visitor_review_path(visitor_review) %></td>
        <td><%= link_to 'Destroy', visitor_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visitor Review', new_visitor_review_path %>

app/views/visitor_reviews/new.html.erb
<h1>New Visitor Review</h1>

<%= render 'form', visitor_review: @visitor_review %>

<%= link_to 'Back', visitor_reviews_path %>

app/views/visitor_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_visitor_review_path(@visitor_review) %> |
<%= link_to 'Back', visitor_reviews_path %>