config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :place_ratings
  resources :visitor_reviews
  resources :places_to_visits
  devise_for :users
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/places_to_visit.rb
class PlacesToVisit < ApplicationRecord
end

app/controllers/places_to_visits_controller.rb
class PlacesToVisitsController < ApplicationController
  before_action :set_places_to_visit, only: [:show, :edit, :update, :destroy]

  # GET /places_to_visits
  # GET /places_to_visits.json
  def index
    @places_to_visits = PlacesToVisit.all
  end

  # GET /places_to_visits/1
  # GET /places_to_visits/1.json
  def show
  end

  # GET /places_to_visits/new
  def new
    @places_to_visit = PlacesToVisit.new
  end

  # GET /places_to_visits/1/edit
  def edit
  end

  # POST /places_to_visits
  # POST /places_to_visits.json
  def create
    @places_to_visit = PlacesToVisit.new(places_to_visit_params)

    respond_to do |format|
      if @places_to_visit.save
        format.html { redirect_to @places_to_visit, notice: 'Places to visit was successfully created.' }
        format.json { render :show, status: :created, location: @places_to_visit }
      else
        format.html { render :new }
        format.json { render json: @places_to_visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places_to_visits/1
  # PATCH/PUT /places_to_visits/1.json
  def update
    respond_to do |format|
      if @places_to_visit.update(places_to_visit_params)
        format.html { redirect_to @places_to_visit, notice: 'Places to visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @places_to_visit }
      else
        format.html { render :edit }
        format.json { render json: @places_to_visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places_to_visits/1
  # DELETE /places_to_visits/1.json
  def destroy
    @places_to_visit.destroy
    respond_to do |format|
      format.html { redirect_to places_to_visits_url, notice: 'Places to visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_places_to_visit
      @places_to_visit = PlacesToVisit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def places_to_visit_params
      params.fetch(:places_to_visit, {})
    end
end

app/helpers/places_to_visits_helper.rb
module PlacesToVisitsHelper
end

app/views/places_to_visits/_form.html.erb
<%= form_with(model: places_to_visit, local: true) do |form| %>
  <% if places_to_visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(places_to_visit.errors.count, "error") %> prohibited this places_to_visit from being saved:</h2>

      <ul>
      <% places_to_visit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places_to_visits/edit.html.erb
<h1>Editing Places To Visit</h1>

<%= render 'form', places_to_visit: @places_to_visit %>

<%= link_to 'Show', @places_to_visit %> |
<%= link_to 'Back', places_to_visits_path %>

app/views/places_to_visits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places To Visits</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places_to_visits.each do |places_to_visit| %>
      <tr>
        <td><%= link_to 'Show', places_to_visit %></td>
        <td><%= link_to 'Edit', edit_places_to_visit_path(places_to_visit) %></td>
        <td><%= link_to 'Destroy', places_to_visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Places To Visit', new_places_to_visit_path %>

app/views/places_to_visits/new.html.erb
<h1>New Places To Visit</h1>

<%= render 'form', places_to_visit: @places_to_visit %>

<%= link_to 'Back', places_to_visits_path %>

app/views/places_to_visits/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_places_to_visit_path(@places_to_visit) %> |
<%= link_to 'Back', places_to_visits_path %>