config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :place_ratings
  resources :visitor_reviews
  resources :places_to_visits
  devise_for :users
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/place_rating.rb
class PlaceRating < ApplicationRecord
end

app/controllers/place_ratings_controller.rb
class PlaceRatingsController < ApplicationController
  before_action :set_place_rating, only: [:show, :edit, :update, :destroy]

  # GET /place_ratings
  # GET /place_ratings.json
  def index
    @place_ratings = PlaceRating.all
  end

  # GET /place_ratings/1
  # GET /place_ratings/1.json
  def show
  end

  # GET /place_ratings/new
  def new
    @place_rating = PlaceRating.new
  end

  # GET /place_ratings/1/edit
  def edit
  end

  # POST /place_ratings
  # POST /place_ratings.json
  def create
    @place_rating = PlaceRating.new(place_rating_params)

    respond_to do |format|
      if @place_rating.save
        format.html { redirect_to @place_rating, notice: 'Place rating was successfully created.' }
        format.json { render :show, status: :created, location: @place_rating }
      else
        format.html { render :new }
        format.json { render json: @place_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /place_ratings/1
  # PATCH/PUT /place_ratings/1.json
  def update
    respond_to do |format|
      if @place_rating.update(place_rating_params)
        format.html { redirect_to @place_rating, notice: 'Place rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @place_rating }
      else
        format.html { render :edit }
        format.json { render json: @place_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /place_ratings/1
  # DELETE /place_ratings/1.json
  def destroy
    @place_rating.destroy
    respond_to do |format|
      format.html { redirect_to place_ratings_url, notice: 'Place rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place_rating
      @place_rating = PlaceRating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_rating_params
      params.fetch(:place_rating, {})
    end
end

app/helpers/place_ratings_helper.rb
module PlaceRatingsHelper
end

app/views/place_ratings/_form.html.erb
<%= form_with(model: place_rating, local: true) do |form| %>
  <% if place_rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place_rating.errors.count, "error") %> prohibited this place_rating from being saved:</h2>

      <ul>
      <% place_rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/place_ratings/edit.html.erb
<h1>Editing Place Rating</h1>

<%= render 'form', place_rating: @place_rating %>

<%= link_to 'Show', @place_rating %> |
<%= link_to 'Back', place_ratings_path %>

app/views/place_ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Place Ratings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @place_ratings.each do |place_rating| %>
      <tr>
        <td><%= link_to 'Show', place_rating %></td>
        <td><%= link_to 'Edit', edit_place_rating_path(place_rating) %></td>
        <td><%= link_to 'Destroy', place_rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place Rating', new_place_rating_path %>

app/views/place_ratings/new.html.erb
<h1>New Place Rating</h1>

<%= render 'form', place_rating: @place_rating %>

<%= link_to 'Back', place_ratings_path %>

app/views/place_ratings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_place_rating_path(@place_rating) %> |
<%= link_to 'Back', place_ratings_path %>